=== oat-sa/tao-core/doc/structures.dtd
<!-- Root Tag -->
<!ELEMENT structures  (( structure )*) >
	<!ELEMENT structure  ( (description)? , (icon)?, sections )>
	
		<!-- The id of the structure -->
		<!ATTLIST structure id ID #REQUIRED>
		<!-- The name of the structure -->
		<!ATTLIST structure name CDATA #REQUIRED>
		<!-- The level of that structure regarding the others (to order them)  -->
		<!ATTLIST structure level CDATA #REQUIRED>
		<!-- What group the structure belongs to -->
		<!ATTLIST structure group CDATA "main">
        <!-- The JS binding to run instead of loading the URL. The binding is the name of an AMD module within TAO -->
        <!ATTLIST structure binding CDATA #IMPLIED>
	
		<!ELEMENT description (#PCDATA)>
		
        <!-- extension icon -->
        <!ELEMENT icon  EMPTY>
        <!-- this is considered a temp solution, eventually we might switch to svg -->
        <!-- source of the icon -->
        <!ATTLIST icon src CDATA #IMPLIED>
        <!-- id of the icon if svg is a sprite -->
        <!ATTLIST icon id CDATA #IMPLIED>
		<!-- extension in which the svg is stored -->
		<!ATTLIST icon ext CDATA #IMPLIED>

		
		<!-- sub division, each section of the extension will be displayed in a separated tab -->
		<!ELEMENT sections  ( section )*>
			<!ELEMENT section  ( trees | actions )*>
				<!-- identifier of the section -->
				<!ATTLIST section id CDATA #REQUIRED>
				<!-- displayed name of the section -->
				<!ATTLIST section name CDATA #REQUIRED>
				<!-- The URL of the action to load -->
				<!ATTLIST section url CDATA #REQUIRED>
				<!-- The policy on how to handle duplicate section keys -->
				<!ATTLIST section policy (merge|override) "merge">
                <!-- The JS binding to run instead of loading the URL. The binding is the name of an AMD module within TAO -->
                <!ATTLIST section binding CDATA #IMPLIED>
                <!-- if a section is disabled -->
                <!ATTLIST section disabled CDATA #IMPLIED>
	
				<!-- The list of trees to load in the section panel -->
				<!ELEMENT trees  ( tree )*>
					<!ELEMENT tree  EMPTY>
					<!-- the name of the tree  -->
					<!ATTLIST tree name CDATA #REQUIRED>
					<!-- the URL to populate the tree with (must return JSON data)  -->
					<!ATTLIST tree dataUrl CDATA #REQUIRED>
					<!-- the URL to execute contextual actions from the tree -->
					<!ATTLIST tree className CDATA #IMPLIED>
					<!-- the name of the main class that resources are instances of in the tree -->
					<!ATTLIST tree
						selectClass CDATA #IMPLIED
						selectInstance CDATA #IMPLIED
						moveInstance CDATA #IMPLIED
						delete CDATA #IMPLIED
						rootNode CDATA #IMPLIED
                        init CDATA #IMPLIED
					>
	
				<!-- The list of contextual actions to load in the section panel -->
				<!ELEMENT actions  ( action )*>
					<!ATTLIST actions
						allowClassActions (true | false) #IMPLIED
					>
					<!ELEMENT action (icon)?>
					<!-- Id of the action -->
					<!ATTLIST action id CDATA #REQUIRED>
                    <!-- Name of the action -->
                    <!ATTLIST action name CDATA #REQUIRED>
					<!-- The URL of the action -->
					<!ATTLIST action url CDATA #IMPLIED>
					<!-- The context of the action: (class|instance|resource|*) -->
					<!ATTLIST action context CDATA #REQUIRED>
					<!-- Reload the complete page if true -->
					<!ATTLIST action reload CDATA #IMPLIED>
                    <!-- the action is disabled if true -->
                    <!ATTLIST action disabled CDATA #IMPLIED>
					<!-- Where to position the action -->
					<!ATTLIST action group CDATA #REQUIRED>
					<!-- DEPRECATED : use binding instead -->
					<!ATTLIST action js CDATA "_load">
					<!-- The JS binding of this action -->
					<!ATTLIST action binding CDATA "_load">

=== oat-sa/tao-core/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../doc/structures.dtd">
<structures>
    <structure id="users" name="Users" level="11" group="settings">
        <description/>
        <icon id="icon-users" src=""/>
        <sections>
            <section id="list_users" name="Manage users" url="/tao/Users/index"/>
            <section id="add_user" name="Add a user" url="/tao/Users/add"/>
            <section id="edit_user" name="Edit a user" url="/tao/Users/edit" disabled="true"/>
            <section id="manage_roles" name="Manage roles" url="/tao/Roles/index">
                <trees>
                    <tree name="Roles library"
                          className="Role"
                          dataUrl="/tao/Roles/getOntologyData"
                          selectClass="role-class-properties"
                          selectInstance="role-properties"
                          delete="role-delete"
                     />
                </trees>
                <actions>
                	<action id="role-class-properties" name="Properties" url="/tao/Roles/editRoleClass" group="content" context="class">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="role-properties" name="Properties"  url="/tao/Roles/editRole" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="role-filter" name="Filter" context="*" group="search" binding="filter">
                        <icon id="icon-filter"/>
                    </action>
                    <action id="role-search" name="Search" url="/tao/Roles/search" context="*" group="search" binding="launchFinder">
                        <icon id="icon-find"/>
                    </action>
                    <action id="role-new" name="New role" url="/tao/Roles/addInstance" context="class" group="content" binding="instanciate">
                        <icon id="icon-tools" src=""/>
                    </action>
                    <action id="role-delete" name="Delete" url="/tao/Roles/delete" context="resource" group="tree" binding="removeNode">
                        <icon id="icon-bin"/>
                    </action>
                    <action id="role-export" name="Export" url="/tao/Export/index" context="resource" group="content">
                        <icon id="icon-export"/>
                    </action>
                </actions>
            </section>
        </sections>
    </structure>

    <structure id="settings" name="Settings" level="8" group="settings">
        <description/>
        <icon id="icon-settings" src=""/>
        <sections>
            <section id="settings_ext_mng" name="Extensions manager" url="/tao/ExtensionsManager/index"/>
            <section id="settings_im_export" name="Ontology" url="/tao/RdfImExport/index"/>
            <section id="settings_versioning" name="File sources" url="/tao/SettingsVersioning/index">
                <trees>
                    <tree name="File sources"
                          className="Repository"
                          dataUrl="/tao/SettingsVersioning/getOntologyData"
                          selectClass="versioning-index"
                          selectInstance="versioning-properties"
                          delete="versioning-delete"
                     />
                </trees>
                <actions>
                	<action id="versioning-index" name="Index" url="/tao/SettingsVersioning/index" group="none" context="class">
                        <icon id=""/>
                    </action>
                    <action id="versioning-properties" name="Properties"  url="/tao/SettingsVersioning/editRepository" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="versioning-new" name="New repository" url="/tao/SettingsVersioning/addInstance" context="class" group="content" binding="instanciate">
                        <icon id="icon-add"/>
                    </action>
                    <action id="versioning-delete" name="Delete" url="/tao/SettingsVersioning/delete" context="instance" group="tree" binding="removeNode">
                        <icon id="icon-bin"/>
                    </action>
                </actions>
            </section>
        </sections>
    </structure>

    <structure id="user_settings" name="User Settings" level="110" group="settings">
        <description/>
        <icon id="icon-user" src=""/>
        <sections>
            <section id="settings_my_settings" name="My settings" url="/tao/UserSettings/properties"/>
            <section id="settings_my_password" name="Change password" url="/tao/UserSettings/password"/>
        </sections>
    </structure>

    <entrypoint id="backoffice" title="Test Developers and Administrators" label="TAO Back Office" url="tao/Main/index">
        <description>
            <![CDATA[Create items, manage item and test banks, organize cohorts and deliveries, prepare reports, set up workflows.]]></description>
    </entrypoint>
</structures>
